'use client';

import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black flex flex-col items-center px-4 py-12 relative overflow-hidden">
      {/* Background image */}
      <div
        className="absolute inset-0 bg-cover bg-center opacity-30"
        style={{
          backgroundImage: "url('/bg-succession.png')",
        }}
      />

      {/* Dark overlay */}
      <div className="absolute inset-0 bg-black opacity-60" />

      {/* Logo - Fixed top left */}
      <div className="fixed top-8 left-8 z-20">
        <Link href="/" className="text-white text-sm tracking-wide font-medium hover:text-[#B5A692] transition-colors">
          Succession Story
        </Link>
      </div>

      {/* Main Content */}
      <div className="relative z-10 w-full max-w-3xl mt-16 pb-24">
        {/* Title */}
        <h1 className="text-4xl md:text-5xl font-heading font-bold mb-8 text-center">
          <span className="text-white">Terms and </span>
          <span className="text-[#B5A692]">Conditions</span>
        </h1>

        {/* Content Container */}
        <div className="bg-gradient-to-b from-black/80 to-black/90 backdrop-blur-sm rounded-2xl p-8 border border-white/10">
          <p className="text-white/60 text-sm mb-6">
            Last Updated: December 2025
          </p>

          <p className="text-white/80 leading-relaxed mb-6">
            By accessing or using Succession Story, you agree to these Terms and Conditions. If you do not agree, please do not use the service.
          </p>

          <div className="space-y-8 text-white/80">
            {/* What This Is */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">What This Is</h2>
              <p className="leading-relaxed mb-3">
                Succession Story is a guided writing experience that helps you put your values, intentions, and personal wishes into words for the people you care about. It is designed to help you explain the meaning behind your decisions, share your life lessons, and leave a thoughtful message your family can return to.
              </p>
              <p className="leading-relaxed">
                This tool helps you reflect, organize your thoughts, and create a polished personal letter in your own voice. It is meant to complement your estate planning, not replace it.
              </p>
            </section>

            {/* What This Is Not */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">What This Is Not</h2>
              <p className="leading-relaxed mb-3">
                Succession Story is not legal, tax, or financial advice. It does not create, change, or override any will, trust, or estate plan. Nothing you write here has legal effect or controls how assets are distributed.
              </p>
              <p className="leading-relaxed">
                This tool does not replace conversations with your family or guidance from an attorney or advisor. It is simply a way to express what matters to you, in your own words.
              </p>
            </section>

            {/* 1. Nature of the Product */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">1. Nature of the Product</h2>
              <p className="leading-relaxed mb-3">
                Succession Story is a digital writing tool designed to help users express personal values, intentions, and legacy messages. It is intended for personal reflection and communication only.
              </p>
              <p className="leading-relaxed mb-3">Succession Story does not:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>Provide legal advice</li>
                <li>Provide tax advice</li>
                <li>Provide financial advice</li>
                <li>Create legal documents</li>
                <li>Replace, amend, or modify wills, trusts, or estate plans</li>
              </ul>
              <p className="leading-relaxed mt-3 font-semibold">
                Nothing entered into or generated by this product has legal effect.
              </p>
            </section>

            {/* 2. No Legal or Tax Effect */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">2. No Legal or Tax Effect</h2>
              <p className="leading-relaxed mb-3">Any content created using Succession Story:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>Does not amend, override, or supplement your will, trust, or estate plan</li>
                <li>Does not constitute legally binding instructions</li>
                <li>Is not enforceable under any estate, probate, or trust law</li>
              </ul>
              <p className="leading-relaxed mt-3">
                You are encouraged to consult a qualified attorney or advisor for legal or estate planning matters.
              </p>
              <p className="leading-relaxed mt-3">
                While Succession Story was created by an attorney, she is not acting as your attorney for any purpose. Your use of this product does not create an attorney client relationship, and no legal representation is provided through this service.
              </p>
              <p className="leading-relaxed mt-3">
                Any information, guidance, or content generated through Succession Story is for personal expression only and is not a substitute for advice from a qualified attorney who is familiar with your specific circumstances. If you require legal advice or representation, you should consult an attorney of your choosing.
              </p>
            </section>

            {/* 3. User Responsibility */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">3. User Responsibility</h2>
              <p className="leading-relaxed mb-3">You are responsible for:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>The accuracy and completeness of the information you provide</li>
                <li>Reviewing and approving any generated content</li>
                <li>How you choose to use, share, or rely on your Succession Story</li>
              </ul>
              <p className="leading-relaxed mt-3">
                Succession Story does not verify user input or validate the accuracy of generated content.
              </p>
            </section>

            {/* 4. AI Generated Content Disclaimer */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">4. AI Generated Content Disclaimer</h2>
              <p className="leading-relaxed mb-3">
                Succession Story uses AI assisted writing tools to help shape user input into a polished narrative.
              </p>
              <p className="leading-relaxed mb-3">You acknowledge that:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>Output is generated based on your inputs</li>
                <li>AI generated content may contain errors or require editing</li>
                <li>Final responsibility for the content rests with you</li>
              </ul>
              <p className="leading-relaxed mt-3">
                Succession Story makes no guarantees regarding tone, accuracy, completeness, or suitability of the output.
              </p>
            </section>

            {/* 5. Privacy and Data Rights */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">5. Privacy and Data Rights</h2>
              <p className="leading-relaxed mb-3">
                Your use of Succession Story is subject to our{' '}
                <Link href="/privacy" className="text-[#B5A692] hover:underline">Privacy Policy</Link>, which explains how we collect, use, store, and delete personal information.
              </p>
              <p className="leading-relaxed mb-3">You acknowledge that:</p>
              <ul className="list-disc list-inside space-y-2 ml-2">
                <li>You control your data and may delete it at any time</li>
                <li>Deletion permanently removes your data and cannot be undone</li>
                <li>Once deleted, your content cannot be recovered</li>
              </ul>
              <p className="leading-relaxed mt-3">
                Your privacy rights may vary depending on your location, including rights under California, Texas, and European Union law.
              </p>
            </section>

            {/* 6. Payment and Access */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">6. Payment and Access</h2>
              <p className="leading-relaxed mb-3">
                Access to Succession Story is provided upon payment, unless otherwise stated.
              </p>
              <p className="leading-relaxed">
                All sales are final unless required by applicable law. We reserve the right to modify pricing, features, or access at any time.
              </p>
            </section>

            {/* 7. Intellectual Property */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
              <p className="leading-relaxed mb-3">
                All website content, branding, software, and materials are owned by Succession Story or its licensors.
              </p>
              <p className="leading-relaxed mb-3">
                You retain full ownership of the personal content you create using the service. By using the product, you grant Succession Story a limited license to process your content solely to provide the service.
              </p>
              <p className="leading-relaxed">
                You may not copy, resell, reverse engineer, or misuse the platform or its materials without permission.
              </p>
            </section>

            {/* 8. Regional Legal Rights */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">8. Regional Legal Rights</h2>

              <h3 className="text-lg font-medium text-white mt-4 mb-2">California Residents</h3>
              <p className="leading-relaxed">
                If you are a California resident, you may have rights under the California Consumer Privacy Act and California Privacy Rights Act, including rights to access, delete, correct, and opt out of the sale or sharing of personal information. Succession Story does not sell or share personal information as defined by California law.
              </p>

              <h3 className="text-lg font-medium text-white mt-4 mb-2">Texas Residents</h3>
              <p className="leading-relaxed">
                If you are a Texas resident, you may have rights under the Texas Data Privacy and Security Act, including rights to access, correct, delete, and opt out of certain processing of personal data.
              </p>

              <h3 className="text-lg font-medium text-white mt-4 mb-2">European Union Residents</h3>
              <p className="leading-relaxed">
                If you are located in the European Union, you may have rights under the General Data Protection Regulation, including rights to access, rectification, erasure, restriction, portability, and objection, as described in our Privacy Policy.
              </p>
            </section>

            {/* 9. Limitation of Liability */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
              <p className="leading-relaxed mb-3">
                Succession Story is provided "as is" and "as available." This is simply a service to help you write a letter. Be reasonable with your expectations.
              </p>
              <p className="leading-relaxed mb-3">
                To the fullest extent permitted by law, Succession Story, its owners and affiliates, will not be liable for any indirect, incidental, consequential, special, or punitive damages, including but not limited to emotional distress or personal outcomes, loss of data, family disputes or misunderstandings, or decisions made based on generated content.
              </p>
              <p className="leading-relaxed mb-3">
                In no event shall the total liability of Succession Story for any claim arising out of or relating to your use of the service exceed the total amount you paid for the product. If this limitation doesn't apply in your jurisdiction, liability will be limited to the maximum extent permitted by applicable law.
              </p>
              <p className="leading-relaxed">
                Your use of the service is at your own discretion and risk.
              </p>
            </section>

            {/* 10. Indemnification */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">10. Indemnification</h2>
              <p className="leading-relaxed">
                You agree to indemnify and hold harmless Succession Story from any claims, damages, losses, or expenses arising from your use of the service or violation of these Terms.
              </p>
            </section>

            {/* 11. Children's Use */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">11. Children's Use</h2>
              <p className="leading-relaxed">
                Succession Story is intended for adults only. Users under the age of 13 are not permitted to use the service.
              </p>
            </section>

            {/* 12. Governing Law */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">12. Governing Law</h2>
              <p className="leading-relaxed">
                These Terms are governed by the laws of the state in which Succession Story operates, without regard to conflict of law principles.
              </p>
            </section>

            {/* 13. Changes to These Terms */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">13. Changes to These Terms</h2>
              <p className="leading-relaxed">
                We may update these Terms from time to time. Continued use of the service constitutes acceptance of the updated Terms.
              </p>
            </section>

            {/* 14. Contact */}
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">14. Contact</h2>
              <p className="leading-relaxed">
                For questions about these Terms, contact us at{' '}
                <a href="mailto:successionstory.now@gmail.com" className="text-[#B5A692] hover:underline">
                  successionstory.now@gmail.com
                </a>.
              </p>
            </section>
          </div>
        </div>

        {/* Back to Home Link */}
        <div className="mt-8 text-center">
          <Link
            href="/"
            className="inline-block px-8 py-3 bg-transparent border border-white text-white rounded-full font-medium hover:bg-white hover:text-black transition-all duration-300"
          >
            Return Home
          </Link>
        </div>
      </div>

      {/* Footer links */}
      <div className="fixed bottom-8 left-0 right-0 flex justify-center gap-8 text-white text-sm z-20">
        <span className="text-[#B5A692]">Terms</span>
        <a href="/privacy" className="hover:text-[#B5A692] transition-colors">Privacy</a>
      </div>
    </div>
  );
}
