export type QuestionType =
  | 'text'
  | 'textarea'
  | 'dropdown'
  | 'multiselect'
  | 'voice'
  | 'multi-dropdown'
  | 'story'
  | 'child-section'
  | 'spouse-section';

export interface Question {
  id: string;
  section: string;
  sectionIndex: number;
  text: string;
  label?: string;
  type: QuestionType;
  required: boolean;
  voiceEnabled?: boolean;
  options?: string[];
  placeholder?: string;
  maxLength?: number;
  helpText?: string;
  allowCustom?: boolean;
  // Story-specific fields
  subtitle?: string;
  storyPrompts?: string[];
  storyTitle?: string;
  allowAddMore?: boolean;
}

export interface Section {
  id: number;
  title: string;
  totalQuestions: number;
}

export const sections: Section[] = [
  { id: 1, title: 'First Things First', totalQuestions: 3 },
  { id: 2, title: 'Guidance For Stewardship', totalQuestions: 9 },
  { id: 3, title: 'My Beliefs and Values', totalQuestions: 6 },
  { id: 4, title: 'My Family', totalQuestions: 9 },
  { id: 5, title: 'Pivotal Experiences In My Life', totalQuestions: 3 },
  { id: 6, title: 'My Legacy', totalQuestions: 5 },
  { id: 7, title: 'Closing Thoughts', totalQuestions: 7 },
];

export const questions: Question[] = [
  // ============================================
  // Section 1: First Things First
  // ============================================
  {
    id: 'q1_1',
    section: 'First Things First',
    sectionIndex: 1,
    text: 'Who is this letter to?',
    label: 'Recipients',
    type: 'dropdown',
    required: false,
    allowCustom: true,
    placeholder: 'Enter Specific Names Or Text',
    options: [
      'My Loved Ones',
      'My Family and Future Generations',
      'My Beautiful Wife',
      'My Loving Husband',
      'My Children and their Children',
    ],
  },
  {
    id: 'q1_2',
    section: 'First Things First',
    sectionIndex: 1,
    text: 'I am creating this Legacy Letter in order to:',
    label: 'Purpose',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'pass along my values and beliefs.',
      'ensure my family knows my wishes.',
      'share my life lessons and experiences.',
      'leave a meaningful legacy.',
      'share with you my values.',
      'express my love and my hopes for the future.',
      'explain why I distributed my estate the way that I did.',
      'share the wisdom I\'ve gathered and my love for each of you.',
      'ensure that my intentions and priorities are understood.',
      'finally say the things I wasn\'t able to say directly.',
    ],
  },
  {
    id: 'q1_3',
    section: 'First Things First',
    sectionIndex: 1,
    text: 'Please share this Legacy Letter with anyone mentioned in it and:',
    label: 'Share List',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'with my immediate family only.',
      'with my extended family.',
      'with my closest friends.',
      'with any of my family and friends.',
      'with future generations of my family.',
      'as a post on my Facebook Page.',
    ],
  },

  // ============================================
  // Section 2: My Beliefs and Values
  // ============================================
  {
    id: 'q2_1',
    section: 'My Beliefs and Values',
    sectionIndex: 3,
    text: 'I fundamentally believe:',
    label: 'Core Beliefs',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'that kindness always matters.',
      'that honesty is the best policy.',
      'that family is everything.',
      'in the Golden Rule.',
      'that our faith in God comes first.',
      'that people are inherently good.',
      'that I am a lifelong student.',
      'that everything happens for a reason.',
      'being is much more important than having.',
      'love conquers all.',
      'that I am the architect of my life.',
      'that there is a God and Jesus Christ is our savior.',
      'that there is one God, singular and eternal.',
      'that there is one God, Allah.',
      'that there is something greater than us.',
    ],
  },
  {
    id: 'q2_2',
    section: 'My Beliefs and Values',
    sectionIndex: 3,
    text: 'Looking back on my life, and who I am today, I believe that I am',
    label: 'My Values',
    type: 'multiselect',
    required: false,
    placeholder: 'Select',
    helpText: 'Select up to four values that describe you best',
    options: [
      'Reliable', 'Responsible', 'Hardworking', 'Disciplined', 'Organized',
      'Resourceful', 'Patient', 'Frugal', 'Persistent', 'Practical',
      'Honest', 'Direct', 'Logical', 'Fair', 'Humble',
      'Ethical', 'Strategic', 'Thoughtful', 'Generous', 'Loving',
      'Empathetic', 'Caring', 'Supportive', 'Charitable', 'Compassionate',
      'Kind-hearted', 'Trustworthy', 'Creative', 'Peaceful',
    ],
  },
  {
    id: 'q2_3',
    section: 'My Beliefs and Values',
    sectionIndex: 3,
    text: 'When others describe me, I\'ve heard them tell me or others that I am:',
    label: 'How Others See Me',
    type: 'multiselect',
    required: false,
    placeholder: 'Select',
    helpText: 'Select up to four values that describe you best',
    options: [
      'Reliable', 'Responsible', 'Hardworking', 'Disciplined', 'Organized',
      'Resourceful', 'Patient', 'Frugal', 'Persistent', 'Practical',
      'Honest', 'Direct', 'Logical', 'Fair', 'Humble',
      'Ethical', 'Strategic', 'Thoughtful', 'Generous', 'Loving',
      'Empathetic', 'Caring', 'Supportive', 'Charitable', 'Compassionate',
      'Kind-hearted', 'Trustworthy', 'Creative', 'Peaceful',
    ],
  },
  {
    id: 'q2_3b',
    section: 'My Beliefs and Values',
    sectionIndex: 3,
    text: 'I think this is true:',
    label: 'Core Truth',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'that kindness always matters.',
      'that honesty is the best policy.',
      'that family is everything.',
      'in the Golden Rule.',
      'that our faith in God comes first.',
      'that people are inherently good.',
      'that I am a lifelong student.',
      'that everything happens for a reason.',
      'being is much more important than having.',
      'love conquers all.',
      'that I am the architect of my life.',
      'that there is a God and Jesus Christ is our savior.',
      'that there is one God, singular and eternal.',
      'that there is one God, Allah.',
      'that there is something greater than us.',
    ],
  },
  {
    id: 'q2_4',
    section: 'My Beliefs and Values',
    sectionIndex: 3,
    text: 'Favorite stories',
    label: 'Favorite stories',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Type Here!',
    subtitle: 'Stories untold tend to fade. Let\'s capture one now, while it\'s still vivid.\n\nThis moment is the youngest you\'ll ever be again. What story do you want remembered? You don\'t need to write a novel. Just respond like you\'re talking to someone you love.\n\nAnswer the first two that resonate with you.',
    storyTitle: 'Story 1',
    storyPrompts: [
      'What\'s a story you\'ve noticed you repeat a lot?',
      'What did Sunday mornings smell like when you were growing up?',
      'What\'s the best financial decision you ever made?',
      'What song instantly takes you back to your childhood?',
      'One thing I\'ve always wanted you to know about me is...',
      'What was the kitchen like in the house where you spent most of your childhood?',
    ],
    allowAddMore: false,
  },
  {
    id: 'q2_4b',
    section: 'My Beliefs and Values',
    sectionIndex: 3,
    text: 'Story 2',
    label: 'Story 2',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Type Here!',
    storyTitle: 'Story 2',
    storyPrompts: [
      'What\'s a tradition you hope your family never forgets?',
      'What advice would you give someone starting their first real job?',
      'People always ask me how I got rich and here\'s the real answer...',
      'Have you ever been in a fist fight? What did you learn?',
      'What do you remember about your first paycheck?',
      'Who is the first person you called after the birth of your child?',
      'Tell me about your first big win — in life, business, or love.',
    ],
    allowAddMore: true,
  },

  // ============================================
  // Section 3: My Family
  // ============================================
  // family_1.PNG - Question 1
  {
    id: 'q3_1',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Family is important to me because:',
    label: 'Family Importance',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'it provided a foundation for identity and belonging.',
      'it felt like home, wherever we were.',
      'it gave us all security, love, and guidance.',
      'it shaped our values for generations.',
      'it made me feel connection to something larger.',
      'it offered a safe space for emotional support.',
      'it provided unconditional love and acceptance.',
      'it weathered the storm through thick and thin.',
      'it\'s where I learned how to love and be loved.',
      'it\'s my foundation and my safe place.',
      'it taught me the value of loyalty and sacrifice.',
      'it gave me people who truly understand me.',
      'it shaped who I am and how I see the world.',
      'it connected me to my heritage and culture.',
      'it gave me a legacy to carry forward.',
    ],
  },
  // family_1.PNG - Question 2
  {
    id: 'q3_2a',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Think of a Family Member who is older than you or a Family Member who passed away. Someone special to you. We\'ll ask you to tell us a little about them on the next page.',
    label: 'Elder Family Member',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    helpText: 'This is an opportunity to make sure stories don\'t get through the generations.',
    options: [
      'Spouse', 'Partner', 'Mother', 'Father',
      'Maternal Grandmother', 'Maternal Grandfather',
      'Paternal Grandmother', 'Paternal Grandfather',
      'Uncle', 'Aunt', 'Child', 'Sibling', 'Friend',
    ],
  },
  // family_1.PNG - Question 3
  {
    id: 'q3_2b',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Enter your Family Member\'s name.',
    label: 'Their Name',
    type: 'text',
    required: false,
    placeholder: 'Type Here!',
  },
  // family_1.PNG - Question 4
  {
    id: 'q3_2c',
    section: 'My Family',
    sectionIndex: 4,
    text: 'If you had to describe your Family Member in a few words, it would be that they were:',
    label: 'Their Qualities',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'courageous', 'gentle', 'wise', 'patient', 'funny',
      'nurturing', 'protective', 'graceful', 'practical', 'thoughtful',
      'loving', 'creative', 'spiritual', 'strong', 'optimistic',
      'fair-minded', 'joyful', 'caring', 'resourceful', 'diplomatic',
      'determined', 'insightful', 'sincere', 'loyal', 'adventurous',
      'generous', 'forgiving', 'empathetic', 'devoted', 'warm-hearted',
    ],
  },
  // family_2.PNG - Elder Family Member Story
  {
    id: 'q3_2d',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Tell us a short story about your elder Family Member',
    label: 'Elder Family Member Story',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Type Here!',
    subtitle: 'Here are ideas for stories about elder Family Members to share. Remember, any story is better than no story.\n\nSelect any 2 to answer. Skip any that don\'t spark anything for you.',
    storyTitle: 'Story 1',
    storyPrompts: [
      '"What did he order when you went out to eat?"',
      '"If I had five more minutes with someone I lost, I\'d tell them..."',
      '"What\'s a smell that instantly brings back a childhood memory?"',
      '"Think of a time your family member said \'I\'m proud of you\'—where were you?"',
      '"What\'s the first room you remember from your grandparents\' house?"',
      '"Did they have a phrase that they always said, and you can hear it in their voice?"',
      '"Who helped you through your hardest time?"',
      '"What tradition, habit, or mindset should stay in the family forever?"',
      '"What\'s a moment from your childhood that still makes you smile?"',
      '"What did your parents or parents teach you without saying a word?"',
      '"What was your last conversation with someone you loved who has passed?"',
      '"What\'s the story behind the oldest object in your home?"',
    ],
    allowAddMore: true,
  },
  // family_3.PNG - Describe Current Family Member
  {
    id: 'q3_3a',
    section: 'My Family',
    sectionIndex: 4,
    text: 'If you had to describe my Family Member in a few words, it would be that they are',
    label: 'Family Importance',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'courageous', 'gentle', 'wise', 'patient', 'funny',
      'nurturing', 'protective', 'graceful', 'practical', 'thoughtful',
      'loving', 'creative', 'spiritual', 'strong', 'optimistic',
      'fair-minded', 'joyful', 'caring', 'resourceful', 'diplomatic',
      'determined', 'insightful', 'sincere', 'loyal', 'adventurous',
      'generous', 'forgiving', 'empathetic', 'devoted', 'warm-hearted',
    ],
  },
  // family_3.PNG - Current Family Member Story
  {
    id: 'q3_3b',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Tell us a short story about your current Family Member',
    label: 'Current Family Member Story',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Type Here!',
    subtitle: 'Select any 2. Now click record and start talking.\n\nHere are ideas for something to share. Remember, any story is better than no story.',
    storyTitle: 'Story 1',
    storyPrompts: [
      '"If we were having coffee right now, what story would you tell me about your childhood?"',
      '"What\'s one story you always end up telling at family gatherings?"',
      '"Think back to your first big job or business deal. What do you remember most?"',
      '"One thing I\'ve always wanted you to know about me is..."',
      '"Tell me about your first big win — in life, business, or love."',
      '"When did you last take a big risk, and what happened?"',
      '"What lesson did you learn the hard way — and never forgot?"',
      '"Someone once told me: \'You\'re not as smart as you think, but you\'re braver than you know.\' Do you have a quote like that stuck in your head forever?"',
      '"What\'s the best compliment you\'ve ever received?"',
      '"What\'s something about your work ethic you hope others will remember?"',
    ],
    helpText: 'Skip the story for now. (Next)',
    allowAddMore: true,
  },
  // family_4.PNG - Children Section (consolidated into single repeatable section)
  {
    id: 'q3_children_section',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Your Children',
    label: 'Children',
    type: 'child-section',
    required: false,
  },
  // family_5.PNG - Spouse Section (consolidated into single repeatable section)
  {
    id: 'q3_spouse_section',
    section: 'My Family',
    sectionIndex: 4,
    text: 'Your Spouse/Partner',
    label: 'Spouse',
    type: 'spouse-section',
    required: false,
  },

  // ============================================
  // Section 4: Pivotal Experiences
  // ============================================
  {
    id: 'q4_1',
    section: 'Pivotal Experiences In My Life',
    sectionIndex: 5,
    text: 'This event had the greatest impact on my life.',
    label: 'Select up to three.',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'what I did to make money.',
      'falling in love.',
      'the births of my children.',
      'the deaths of loved ones.',
      'getting married.',
      'going through a divorce.',
      'starting my career.',
      'losing my job.',
      'moving to a new city or country.',
      'buying my first home.',
      'battling illness and healing.',
      'surviving a financial crisis.',
      'building a business.',
      'adopting a child.',
      'reconnecting with family.',
      'volunteering in my community.',
      'achieving a major goal.',
      'going to college.',
      'becoming a grandparent.',
      'retiring from work.',
    ],
  },
  {
    id: 'q4_2',
    section: 'Pivotal Experiences In My Life',
    sectionIndex: 5,
    text: 'I am most proud of...',
    label: 'Greatest Pride',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'the family I raised.',
      'my professional achievements.',
      'the person I\'ve become.',
      'the ways I\'ve helped others.',
      'my resilience in tough times.',
      'how I\'ve learned from my mistakes.',
      'my marriage and partnership.',
      'my children\'s accomplishments.',
      'serving my community.',
      'building lasting friendships.',
      'my faith and spiritual journey.',
      'my commitment to my values.',
      'how I\'ve grown wiser with age.',
      'mentoring younger people.',
      'creating financial security.',
      'staying true to who I am.',
    ],
  },
  {
    id: 'q4_3',
    section: 'Pivotal Experiences In My Life',
    sectionIndex: 5,
    text: 'Give a short example or story about a pivotal moment in your life. This is probably a story that you find yourself repeating.',
    label: 'Pivotal Story',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Start recording',
    subtitle: 'Choose the first one that you connect to, and start talking.',
    storyTitle: 'Story 1',
    storyPrompts: [
      'What\'s a story you\'ve noticed you repeat a lot?',
      'What\'s the best financial decision you ever made?',
      'One thing I\'ve always wanted you to know about me is...',
      'What advice would you give someone starting their first job?',
      'People always ask me how I got rich and here\'s the real answer...',
      'What do you remember about your first paycheck?',
      'Tell me about your first big win — in life, business, or love.',
      'How did becoming a parent change you?',
      'What is a story from your military service that you\'ll carry with you always?',
      'What lessons did you learn when you went away to college?',
    ],
    allowAddMore: true,
  },

  // ============================================
  // Section 5: Guidance for Stewardship
  // ============================================
  {
    id: 'q5_1',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'I want my heirs to make the most of any inheritance by:',
    label: 'Inheritance Guidance',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'investing wisely for long-term growth.',
      'saving at least 60% of it for future security.',
      'pay off their home mortgage.',
      'using it to pursue further education.',
      'traveling and expanding their horizons.',
      'immediately hire a financial advisor who is a fiduciary.',
      'using at least 10% to support causes they care about.',
      'purchasing a home to build stability.',
      'helping family members in times of need.',
      'paying off debts and becoming debt-free.',
      'setting aside money for emergencies.',
      'starting or growing a business.',
      'planning for retirement.',
      'living below their means to preserve wealth.',
    ],
  },
  {
    id: 'q5_2',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'It\'s important to me that my family understands the following about my financial intentions and values...',
    label: 'Financial Values',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'I value education over material wealth.',
      'Wealth is a tool, not an identity.',
      'Family unity matters more than money.',
      'I want them to avoid conflicts over money.',
      'I believe in generosity balanced with wisdom.',
      'Financial independence is important.',
      'Our family name carries responsibility.',
      'I want them to stay humble.',
      'I hope they help those less fortunate.',
      'Invest in experiences, not just possessions.',
      'Honesty and integrity matter in financial dealings.',
      'Wealth should be used to create opportunities.',
    ],
  },
  {
    id: 'q5_3',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'Regarding financial literacy, I hope my heirs will:',
    label: 'Financial Literacy Hopes',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'spend the time to learn how to invest wisely.',
      'understand budgeting and saving.',
      'seek out financial education.',
      'teach their own children about money.',
      'ask questions and keep learning.',
      'know how taxes affect wealth.',
      'avoid high-interest debt.',
      'read books about personal finance.',
      'talk openly about money with family.',
      'stay cautious of financial scams.',
      'consult financial advisors.',
      'understand how credit works.',
      'plan for retirement early.',
      'live within their means.',
      'build an emergency fund.',
    ],
  },
  {
    id: 'q5_5',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'When it comes to personal finance, here is the advice I want to pass on based on what I\'ve learned over the years:',
    label: 'Financial Advice',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'Spend less than you earn and save consistently.',
      'Live on a written budget.',
      'Avoid debt whenever possible.',
      'Start investing early and let compound interest work.',
      'Own a piece of the market through low-cost index funds.',
      'Keep investing simple and don\'t chase trends.',
      'Stay calm when markets go up and down.',
      'Focus on long-term goals, not short-term noise.',
      'Build an emergency fund before investing aggressively.',
      'Make decisions when calm, not emotional.',
      'Don\'t try to time the market.',
      'Diversify to reduce risk.',
      'If you don\'t understand it, don\'t invest in it.',
      'Wealth is built slowly, not overnight.',
      'Protect assets through estate planning and insurance.',
      'Give generously — money has purpose.',
    ],
  },
  {
    id: 'q5_6',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'I wish to provide the following general guidance for my heirs to make the most of their inheritance:',
    label: 'Inheritance Wishes',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'Use this inheritance to build a strong foundation.',
      'Invest thoughtfully with long-term perspective.',
      'Seek professional financial advice.',
      'Pay off debt and avoid new obligations.',
      'Spend on experiences that create memories.',
      'Use resources to pursue education or career goals.',
      'Remember wealth is a tool, not a destination.',
      'Make choices that align with your values.',
      'Set aside funds for emergencies.',
      'Share your good fortune through generosity.',
      'Be mindful not to let money change who you are.',
      'Preserve and grow this for the next generation.',
      'Give back to your community.',
      'Stay humble, no matter your wealth.',
      'Value people over possessions.',
    ],
  },
  {
    id: 'q5_9_asset',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'As for:',
    label: 'Asset Type',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    helpText: 'Now is your chance to tell the story behind each gift.',
    options: [
      'any real property',
      'any cash',
      'the house',
      'the family house',
      'the rental property',
      'commercial properties',
      'my business',
      'my retirement account',
      'liquid assets',
      'my stock account',
      'my family heirloom',
      'my car',
      'my gold and silver',
    ],
  },
  {
    id: 'q5_9_guidance',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'Keep in mind that:',
    label: 'Asset Guidance',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'it remain in the family and never be sold.',
      'it be passed down to your children.',
      'it be used as a family vacation home.',
      'it be rented out for family expenses.',
      'it be sold and proceeds divided among heirs.',
      'it be sold only if financially necessary.',
      'it be preserved as a legacy property.',
      'it be maintained and kept in good condition.',
      'it be held in trust for future family use.',
      'it be donated to a cause I care about.',
      'it be the setting for annual family reunions.',
    ],
  },
  {
    id: 'q5_8',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: '',
    label: 'Gift Story',
    type: 'voice',
    voiceEnabled: true,
    required: false,
    placeholder: 'Type or Talk Here',
    helpText: 'One Succession Story writer said, "As for the rental property, keep in mind that they are a business and if you\'re not good at the business either partner with someone who is, or sell them smart and move on. Don\'t let those houses become a burden. If they\'re too much to manage, sell and invest the money. I once heard it said, \'Thanksgiving is family, speaking of which your drain. Don\'t repeat that.\'" Another said, "As for the commercial property, keep in mind that your mother and I touched and improved every inch of it ourselves. We had an agent but we ended up negotiating the deal ourselves. We talked the sellers into financing it for us, and ended up being life-long partners and friends with them. We spent more time there than we did at home. Make the most of it." Another said, "As for our home, keep in mind that the water shutoff is in the freeze proof pit by the side of the house." Another said, "As for my brokerage account, keep in mind that there is enough in there for you to invest most of it, and still buy yourself something nice. I noticed that you never did this. Spend $5,000 of it and splurge on something that makes you feel good. A nice piece of art, or a first class ticket, whatever you want. I want that for you."',
  },

  // ============================================
  // Section 6: My Legacy
  // ============================================
  {
    id: 'q6_1',
    section: 'My Legacy',
    sectionIndex: 6,
    text: 'I hope to be remembered for:',
    label: 'Remembered For',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'how deeply I loved.',
      'the way I showed up for others.',
      'the values I lived by.',
      'how I made people feel seen and heard.',
      'my honesty and integrity.',
      'my generosity with time and resources.',
      'my sense of humor.',
      'the way I brought people together.',
      'my faith and spiritual convictions.',
      'the traditions I passed down.',
      'how I stayed true to myself.',
      'the lessons I taught my family.',
      'the way I listened.',
      'my strength during hard times.',
      'my creativity and unique perspective.',
      'the warmth I brought into every space.',
      'my ability to forgive.',
      'the joy I found in simple things.',
      'how I served my community.',
      'my love for learning.',
    ],
  },
  {
    id: 'q6_2',
    section: 'My Legacy',
    sectionIndex: 6,
    text: 'The causes that have always been important to me are:',
    label: 'Important Causes',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'advancing social justice.',
      'protecting the environment.',
      'promoting education and mentorship.',
      'supporting healthcare and well-being.',
      'helping the homeless.',
      'animal welfare.',
      'mental health awareness.',
      'ending hunger and poverty.',
      'supporting veterans.',
      'fostering community arts.',
      'children\'s welfare.',
      'disaster relief efforts.',
      'clean water initiatives.',
      'women\'s rights.',
      'literacy programs.',
      'elder care and advocacy.',
      'affordable housing.',
      'religious freedom.',
      'youth sports and development.',
    ],
  },
  {
    id: 'q6_3',
    section: 'My Legacy',
    sectionIndex: 6,
    text: 'I hope my family will carry forward this guiding purpose:',
    label: 'Family Purpose',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'Build generational wealth',
      'Be wealthier as a family 100 years from now',
      'Honor our roots and build our future',
      'Live with integrity and intention',
      'Grow love, legacy, and leadership',
      'Protect and pass down wisdom',
      'Spread the word of God',
      'Put education first',
      'Uplift every generation',
      'Be stewards of faith and fortune',
      'Nurture character over comfort',
      'Leave every place better than we found it',
      'Give generously, live humbly',
      'Invest in people and purpose',
      'Lead with love and loyalty',
      'Preserve our story, protect our values',
      'Pass on more than possessions',
    ],
  },
  {
    id: 'q6_4',
    section: 'My Legacy',
    sectionIndex: 6,
    text: 'What does it mean to be part of this family? (Select up to 5)',
    label: 'Family Core Values',
    type: 'multiselect',
    required: false,
    placeholder: 'Select up to 5 values',
    options: [
      'Faith', 'Family', 'Integrity', 'Hard Work', 'Love',
      'Loyalty', 'Service', 'Education', 'Generosity', 'Humility',
      'Perseverance', 'Respect', 'Gratitude', 'Courage', 'Kindness',
      'Honesty', 'Wisdom', 'Unity', 'Hope', 'Compassion',
    ],
  },
  {
    id: 'q6_5',
    section: 'My Legacy',
    sectionIndex: 6,
    text: 'If my family created a physical memorial in my honor:',
    label: 'Memorial Preference',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'my ashes scattered in a beautiful location',
      'a park bench beneath the trees',
      'a constellation named after me',
      'a grave stone is enough',
      'ashes mounted into jewelry for family',
      'a child who carries my name',
      'a quiet visit to where I rest',
      'a tree planted in my honor',
      'a plaque at our local library',
      'a scholarship fund at my alma mater',
      'a memorial garden in a favorite place',
      'an annual gathering in my name',
      'a sculpture or public art piece',
    ],
  },

  // ============================================
  // Section 7: Closing Thoughts
  // ============================================
  {
    id: 'q7_1',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'Above all, I want you to know:',
    label: 'Final Message',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'how much I love you.',
      'that I\'ve always been proud of you.',
      'that my love doesn\'t end with this letter.',
      'how grateful I am to have had you in my life.',
      'that I see the best parts of me in you.',
      'that you made my life better by being in it.',
      'how much joy you brought me.',
      'that you were one of my greatest gifts.',
      'that our memories are my treasures.',
      'that I trust you to carry my values forward.',
      'how proud I am of the person you\'ve become.',
      'that love is what matters most.',
      'that you are enough, exactly as you are.',
      'that I believe in you.',
      'that I love you — always.',
    ],
  },
  {
    id: 'q7_2',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'If you ever find yourself in a hard season, remember:',
    label: 'Words of Comfort',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'you\'ve made it through hard times before.',
      'you are stronger than you think.',
      'you are never alone.',
      'I\'ve been through darkness too, and found my way.',
      'love surrounds you, even in silence.',
      'you can begin again.',
      'hope always returns.',
      'you don\'t have to carry everything yourself.',
      'there\'s no shame in asking for help.',
      'this moment will pass.',
      'your story isn\'t over yet.',
      'healing is never linear.',
      'my love is still with you.',
      'you matter.',
    ],
  },
  {
    id: 'q7_3',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'My advice for handling challenges in life is:',
    label: 'Life Advice',
    type: 'multiselect',
    required: false,
    placeholder: 'Select all that apply',
    options: [
      'stay calm and take things one step at a time.',
      'lean on family and friends when you need help.',
      'remember that hard times don\'t last forever.',
      'keep faith in yourself and something greater.',
      'look for the lesson in every hardship.',
      'take care of your mental health.',
      'never be afraid to ask for help.',
      'focus on what you can control.',
      'believe that better days will come.',
      'keep a sense of humor, even in tough times.',
      'be gentle with yourself during struggles.',
      'forgive yourself for mistakes.',
      'trust that time can heal wounds.',
      'find comfort in small daily routines.',
    ],
  },
  {
    id: 'q7_4',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'One message I want to pass on to the next generation:',
    label: 'Message to Future',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'You are loved — always, and without condition.',
      'Keep going — your life has purpose.',
      'Stay true to your values no matter the pressure.',
      'Never stop learning, growing, and becoming.',
      'Be kind — even when it\'s hard.',
      'Choose love over fear.',
      'Stay curious.',
      'Stand up for what\'s right.',
      'Keep your word.',
      'Stay close to people who know your heart.',
      'Laugh often and out loud.',
      'Apologize quickly and forgive freely.',
      'Chase your dreams with courage.',
      'Trust that you are enough.',
      'Give more than you take.',
      'Leave the world better than you found it.',
    ],
  },
  {
    id: 'q7_5',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'What name do you want to use to sign your letter?',
    label: 'Signature Name',
    type: 'text',
    required: false,
    placeholder: 'Enter your name',
  },
  {
    id: 'q7_6',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'One last thing I want you to know:',
    label: 'Final Words',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'thank you for loving me.',
      'thank you for letting me love you.',
      'I carry no regrets about loving you.',
      'I leave you with my full heart.',
      'I\'m proud of our time together.',
      'I\'ll always be with you in spirit.',
      'this letter is a part of me I\'m leaving behind.',
      'I hope you\'ll find comfort in these words.',
      'keep our traditions alive.',
      'love each other fiercely.',
      'create your own legacy.',
      'trust your heart.',
      'I love you — always.',
    ],
  },
  {
    id: 'q7_7',
    section: 'Closing Thoughts',
    sectionIndex: 7,
    text: 'Closing for your letter:',
    label: 'Letter Closing',
    type: 'dropdown',
    required: false,
    placeholder: 'Select',
    options: [
      'With all my love',
      'Love always',
      'Forever yours',
      'Holding you in my heart',
      'Peace and love',
      'With a full heart',
      'All my love, now and always',
      'Until we meet again',
      'May love be your guide',
      'Sincerely',
      'Yours truly',
      'Faithfully',
      'With gratitude',
      'Ever yours',
      'In the spirit of our family',
      'Passing the torch',
      'From my life to yours',
    ],
  },
];

// Helper function to get questions by section
export const getQuestionsBySection = (sectionIndex: number): Question[] => {
  return questions.filter(q => q.sectionIndex === sectionIndex);
};

// Helper function to get section info
export const getSectionByIndex = (index: number): Section | undefined => {
  return sections.find(s => s.id === index);
};