export type QuestionType =
  | 'text'
  | 'textarea'
  | 'dropdown'
  | 'multiselect'
  | 'voice'
  | 'multi-dropdown'
  | 'story'
  | 'child-section'
  | 'spouse-section'
  | 'asset-section'
  | 'handwriting-style';

export interface Question {
  id: string;
  section: string;
  sectionIndex: number;
  text: string;
  label?: string;
  type: QuestionType;
  required: boolean;
  voiceEnabled?: boolean;
  options?: string[];
  placeholder?: string;
  maxLength?: number;
  helpText?: string;
  allowCustom?: boolean;
  maxSelections?: number;
  // Story-specific fields
  subtitle?: string;
  storyPrompts?: string[];
  storyTitle?: string;
  allowAddMore?: boolean;
  // Image for visual questions
  imageUrl?: string;
}

export interface Section {
  id: number;
  title: string;
  totalQuestions: number;
}

export const sections: Section[] = [
  { id: 1, title: 'First Things First', totalQuestions: 3 },
  { id: 2, title: 'Guidance For Stewardship', totalQuestions: 4 },
  { id: 3, title: 'The Story Behind My Gifts', totalQuestions: 1 },
  { id: 4, title: 'My Beliefs and Values', totalQuestions: 5 },
  { id: 5, title: 'My Family', totalQuestions: 9 },
  { id: 6, title: 'Pivotal Experiences In My Life', totalQuestions: 3 },
  { id: 7, title: 'My Legacy', totalQuestions: 5 },
  { id: 8, title: 'Final Thoughts', totalQuestions: 7 },
  { id: 9, title: 'Tone & Voice of Questionnaire', totalQuestions: 18 },
];

export const questions: Question[] = [
  // ============================================
  // Section 1: First Things First
  // ============================================
  {
    id: 'q1_1',
    section: 'First Things First',
    sectionIndex: 1,
    text: 'Dear ______',
    label: 'Who is this letter to?',
    type: 'dropdown',
    required: false,
    allowCustom: true,
    placeholder: 'Say it in your own words (you may copy and paste to combine the above answer options)',
    options: [
      'My Loved Ones',
      'My Family and Future Generations',
      'My Beautiful Wife',
      'My Loving Husband',
      'My Children and their Children',
    ],
  },
  {
    id: 'q1_2',
    section: 'First Things First',
    sectionIndex: 1,
    text: 'I am creating this Legacy Letter in order to:',
    label: 'Purpose',
    type: 'dropdown',
    required: false,
    placeholder: 'Say it in your own words.',
    options: [
      'pass along my values and beliefs.',
      'ensure my family knows my wishes.',
      'share my life lessons and experiences.',
      'leave a meaningful legacy.',
      'share with you my values.',
      'express my love and my hopes for the future.',
      'explain why I distributed my estate the way that I did.',
      'share the wisdom I\'ve gathered and my love for each of you.',
      'ensure that my intentions and priorities are understood.',
      'finally say the things I wasn\'t able to say directly.',
    ],
  },
  {
    id: 'q1_3',
    section: 'First Things First',
    sectionIndex: 1,
    text: 'Please share this Legacy Letter with anyone mentioned in it and:',
    label: 'Share List',
    type: 'dropdown',
    required: false,
    placeholder: 'Say it in your own words.',
    allowCustom: true,
    options: [
      'with my immediate family only.',
      'with my extended family.',
      'with my closest friends.',
      'with any of my family and friends.',
      'with future generations of my family.',
      'as a post on my Facebook Page.',
    ],
  },

  // ============================================
  // Section 2: My Beliefs and Values
  // ============================================
  {
    id: 'q2_2',
    section: 'My Beliefs and Values',
    sectionIndex: 4,
    text: 'Looking back on my life, and who I am today, I believe that I am:',
    label: 'Select up to 5',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    helpText: 'Select up to four values that describe you best',
    allowCustom: true,
    options: [
      'Reliable', 'Responsible', 'Hardworking', 'Disciplined', 'Organized',
      'Resourceful', 'Punctual', 'Efficient', 'Diligent', 'Patient',
      'Frugal', 'Methodical', 'Persistent', 'Practical', 'Productive',
      'Focused', 'Careful', 'Accurate', 'Thorough', 'Respectful',
      'Cooperative', 'Honest', 'Direct', 'Logical', 'Fair',
      'Humble', 'Balanced', 'Dependable', 'Ethical', 'Strategic',
      'Modest', 'Clear-minded', 'Level-headed', 'Analytical', 'Adaptable',
      'Systematic', 'Rational', 'Intentional', 'Steady', 'Accountable',
      'Thoughtful', 'Observant', 'Humorous', 'Attentive', 'Constructive',
      'Tactful', 'Consistent', 'Grounded', 'Generous', 'Loving',
      'Light-Hearted', 'Inclusive', 'Empathetic', 'Caring', 'Supportive',
      'Helpful', 'Engaged', 'Charitable', 'Service-oriented', 'Collaborative',
      'Fair-minded', 'Neighborly', 'Compassionate', 'Involved', 'Kind-hearted',
      'Welcoming', 'Connected', 'Trustworthy', 'Approachable', 'Admired',
      'Open-minded', 'Unified', 'Peaceful', 'Diplomatic', 'Encouraging',
      'Creative', 'A Team Player', 'Socially Responsible',
    ],
  },
  {
    id: 'q2_3',
    section: 'My Beliefs and Values',
    sectionIndex: 4,
    text: 'When others describe me, I\'ve heard them tell me or others that I am:',
    label: 'How Others See Me',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    helpText: 'Select up to four values that describe you best',
    allowCustom: true,
    options: [
      'Reliable', 'Responsible', 'Hardworking', 'Disciplined', 'Organized',
      'Resourceful', 'Punctual', 'Efficient', 'Diligent', 'Patient',
      'Frugal', 'Methodical', 'Persistent', 'Practical', 'Productive',
      'Focused', 'Careful', 'Accurate', 'Thorough', 'Respectful',
      'Cooperative', 'Honest', 'Direct', 'Logical', 'Fair',
      'Humble', 'Balanced', 'Dependable', 'Ethical', 'Strategic',
      'Modest', 'Clear-minded', 'Level-headed', 'Analytical', 'Adaptable',
      'Systematic', 'Rational', 'Intentional', 'Steady', 'Accountable',
      'Thoughtful', 'Observant', 'Humorous', 'Attentive', 'Constructive',
      'Tactful', 'Consistent', 'Grounded', 'Generous', 'Loving',
      'Light-Hearted', 'Inclusive', 'Empathetic', 'Caring', 'Supportive',
      'Helpful', 'Engaged', 'Charitable', 'Service-oriented', 'Collaborative',
      'Fair-minded', 'Neighborly', 'Compassionate', 'Involved', 'Kind-hearted',
      'Welcoming', 'Connected', 'Trustworthy', 'Approachable', 'Admired',
      'Open-minded', 'Unified', 'Peaceful', 'Diplomatic', 'Encouraging',
      'Creative', 'A Team Player', 'Socially Responsible',
    ],
  },
  {
    id: 'q2_5',
    section: 'My Beliefs and Values',
    sectionIndex: 4,
    text: 'Which of these speaks to you?',
    label: 'Values That Speak To Me',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Kindness: Treat people gently; everyone is fighting unseen battles.',
      'Gratitude: Be thankful for the small, everyday moments.',
      'Patience: Good things—and understanding—take time.',
      'Simplicity: Happiness doesn\'t come from having more things.',
      'Humility: No one knows everything; keep learning.',
      'Faith: Belief in something larger—spirituality, God, or purpose—guides life.',
      'Integrity: Always try to do what\'s right, even if it\'s hard.',
      'Honesty: Speak truthfully, with compassion.',
      'Family bonds: Relationships with family are treasures worth nurturing.',
      'Forgiveness: Holding onto resentment weighs you down.',
      'Loyalty: Stand by those you love.',
      'Service: Give back; help your community and others in need.',
      'Perseverance: Keep going, even when life gets hard.',
      'Respect: Treat all people with dignity, regardless of differences.',
      'Contentment: Appreciate what you have rather than longing for what you don\'t.',
      'Frugality: Save and spend wisely; waste nothing.',
      'Joy: Find moments of laughter and delight daily.',
      'Responsibility: Own your actions and their consequences.',
      'Empathy: Understand others\' feelings and perspectives.',
      'Resilience: Life has storms; you can weather them and heal.',
      'Generosity: Share your blessings—time, resources, love.',
      'Wisdom: Learn from mistakes, and help others avoid them.',
      'Hard work: A strong work ethic builds character and opportunities.',
      'Hope: Believe in brighter days ahead.',
      'Trustworthiness: Be someone others can rely on.',
      'Tolerance: Embrace differences; the world is richer for them.',
      'Open-mindedness: Don\'t stop growing or considering new ideas.',
      'Peace: Avoid unnecessary conflict; seek harmony.',
      'Love: Above all, love deeply and express it freely.',
    ],
  },
  {
    id: 'q2_4',
    section: 'My Beliefs and Values',
    sectionIndex: 4,
    text: 'Favorite Stories',
    label: 'Favorite Stories',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Say it in your own words. Voice-to-Text highly recommended.',
    subtitle: 'Stories untold tend to fade. Let\'s capture one now, while it\'s still vivid.\n\nAnswer the first of the prompts that resonates with you.',
    storyTitle: 'Story 1',
    storyPrompts: [
      'What\'s a story you\'ve noticed you repeat a lot?',
      'What did Sunday mornings smell like when you were growing up?',
      'What\'s the best financial decision you ever made?',
      'What song instantly takes you back to your childhood?',
      'One thing I\'ve always wanted you to know about me is...',
      'What was the kitchen like in the house where you spent most of your childhood?',
      'The last concert or live show I attended was memorable because…',
    ],
    allowAddMore: false,
  },
  {
    id: 'q2_4b',
    section: 'My Beliefs and Values',
    sectionIndex: 4,
    text: 'Story 2',
    label: 'Story 2',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Say it in your own words. Voice-to-Text highly recommended.',
    subtitle: 'This moment is the youngest you\'ll ever be again. What story do you want remembered? You don\'t need to write a novel. Just respond like you\'re talking to someone you love.\n\nIf one of these prompts makes you smile, start with that one.',
    storyTitle: 'Story 2',
    storyPrompts: [
      'What\'s a tradition you hope your family never forgets?',
      'What advice would you give someone starting their first real job?',
      'People always ask me how I got rich and here\'s the real answer...',
      'Have you ever been in a fist fight? What did you learn?',
      'What do you remember about your first paycheck?',
      'Who is the first person you called after the birth of your child?',
      'Tell me about your first big win — in life, business, or love.',
      'If I could change one thing about my military service…',
      'If I could re-live one of my college moments, it would be…',
    ],
    allowAddMore: true,
  },

  // ============================================
  // Section 3: My Family
  // ============================================
  // family_1.PNG - Question 1
  {
    id: 'q3_1',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Family is important to me because:',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'it provided a foundation for identity, belonging, emotional support, and well-being.',
      'it felt like home, wherever we were.',
      'it gave us all security, love, and guidance.',
      'it shaped our values, beliefs, and behaviors, for generations.',
      'it made me feel belonging and connection to something larger than myself.',
      'it offered a safe space for emotional expression and support.',
      'it provided unconditional love, encouragement, and acceptance.',
      'it weathered the storm through thick and thin.',
      'it was the only place I felt stable.',
      'it gave me unconditional love and acceptance.',
      'it\'s where I learned how to love and be loved.',
      'it\'s my foundation and my safe place.',
      'it taught me the value of loyalty and sacrifice.',
      'it\'s where I learned resilience and strength.',
      'it gave me people who truly understand me.',
      'it\'s where I can always be myself.',
      'it shaped who I am and how I see the world.',
      'it connected me to my heritage and culture.',
      'it\'s where I learned to forgive and grow.',
      'it gives me purpose, carrying forward the family name and bloodline.',
      'it gives me certainty of who I can trust.',
      'it showed me how to care for others.',
      'it\'s where I found laughter, even in hard times.',
      'it gave me traditions that bring me joy.',
      'it reminds me of what truly matters.',
      'it\'s where I learned responsibility and commitment.',
      'it gave me purpose beyond myself.',
      'it taught me how to be patient and kind.',
      'it helped me face life\'s challenges with courage.',
      'it gave me security and comfort.',
      'it showed me how to build lasting relationships.',
      'it taught me to appreciate the little things.',
      'it\'s where I learned about respect and boundaries.',
      'it kept me grounded through successes and failures.',
      'it gave me countless precious memories.',
      'it\'s where I learned the value of hard work.',
      'it taught me how to communicate and listen.',
      'it showed me what it means to sacrifice for others.',
      'it connected me to something bigger than myself.',
      'it\'s where I learned to cherish both silence and conversation.',
      'it made me feel like I belong.',
      'it gave me a legacy to carry forward.',
      'it taught me that love often means showing up.',
    ],
  },
  // family_1.PNG - Question 2
  {
    id: 'q3_2a',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Think of a Family Member who is older than you or a Family Member who passed away. Someone special to you. We will ask you to tell us a little about them below.',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Maternal Grandmother', 'Maternal Grandfather',
      'Paternal Grandmother', 'Paternal Grandfather',
      'Mother', 'Father',
      'Spouse', 'Partner',
      'Uncle', 'Aunt', 'Child', 'Sibling', 'Friend',
    ],
  },
  // family_1.PNG - Question 3
  {
    id: 'q3_2b',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Enter your Family Member\'s name.',
    type: 'text',
    required: false,
    placeholder: 'Type Here',
  },
  // family_2.PNG - Elder Family Member Story
  {
    id: 'q3_2d',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Tell us a short story about your elder Family Member',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Say it in your own words. Voice-to-Text highly recommended.',
    subtitle: 'Here are ideas for stories about elder Family Members to share. Remember, any story is better than no story.\n\nSelect any 2 to answer. Skip any that don\'t spark anything for you.',
    storyTitle: 'Story 1',
    storyPrompts: [
      '"What did he order when you went out to eat?"',
      '"If I had five more minutes with someone I lost, I\'d tell them..."',
      '"What\'s a smell that instantly brings back a childhood memory?"',
      '"Think of a time your family member said \'I\'m proud of you\'—where were you?"',
      '"What\'s the first room you remember from your grandparents\' house?"',
      '"Did they have a phrase that they always said, and you can hear it in their voice?"',
      '"Who helped you through your hardest time?"',
      '"What tradition, habit, or mindset should stay in the family forever?"',
      '"What\'s a moment from your childhood that still makes you smile?"',
      '"What did your parents or parents teach you without saying a word?"',
      '"What was your last conversation with someone you loved who has passed?"',
      '"What\'s the story behind the oldest object in your home?"',
    ],
    allowAddMore: true,
  },
  // family_3.PNG - Current Family Member Story
  {
    id: 'q3_3b',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Tell us a short story about your current Family Member',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Say it in your own words. Voice-to-Text highly recommended.',
    subtitle: 'Select any 2. Now click record and start talking.\n\nHere are ideas for something to share. Remember, any story is better than no story.',
    storyTitle: 'Story 1',
    storyPrompts: [
      '"If we were having coffee right now, what story would you tell me about your childhood?"',
      '"What\'s one story you always end up telling at family gatherings?"',
      '"Think back to your first big job or business deal. What do you remember most?"',
      '"One thing I\'ve always wanted you to know about me is..."',
      '"Tell me about your first big win — in life, business, or love."',
      '"When did you last take a big risk, and what happened?"',
      '"What lesson did you learn the hard way — and never forgot?"',
      '"Someone once told me: \'You\'re not as smart as you think, but you\'re braver than you know.\' Do you have a quote like that stuck in your head forever?"',
      '"What\'s the best compliment you\'ve ever received?"',
      '"What\'s something about your work ethic you hope others will remember?"',
    ],
    helpText: 'Skip the story for now. (Next)',
    allowAddMore: true,
  },
  // family_4.PNG - Children Section (consolidated into single repeatable section)
  {
    id: 'q3_children_section',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Your Children',
    label: 'Children',
    type: 'child-section',
    required: false,
  },
  // family_5.PNG - Spouse Section (consolidated into single repeatable section)
  {
    id: 'q3_spouse_section',
    section: 'My Family',
    sectionIndex: 5,
    text: 'Your Spouse/Partner',
    label: 'Spouse',
    type: 'spouse-section',
    required: false,
  },

  // ============================================
  // Section 4: Pivotal Experiences
  // ============================================
  {
    id: 'q4_1',
    section: 'Pivotal Experiences In My Life',
    sectionIndex: 6,
    text: 'This event had the greatest impact on my life.',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    helpText: 'Select up to three',
    options: [
      'what I did to make money.',
      'falling in love.',
      'the births of my children.',
      'the deaths of loved ones.',
      'getting married.',
      'going through a divorce.',
      'starting my career.',
      'losing my job.',
      'moving to a new city or country.',
      'buying my first home.',
      'battling illness and healing.',
      'surviving a financial crisis.',
      'building a business.',
      'adopting a child.',
      'reconnecting with family.',
      'volunteering in my community.',
      'achieving a major goal.',
      'going to college.',
      'learning a new language.',
      'becoming a grandparent.',
      'facing a natural disaster.',
      'retiring from work.',
      'winning an award or honor.',
      'discovering a new passion.',
      'helping someone through hardship.',
      'learning forgiveness.',
      'proving myself.',
      'facing discrimination or injustice.',
      'changing my career path.',
      'experiencing spiritual growth.',
      'creating a work of art.',
      'being part of a social movement.',
      'finding unexpected friendship.',
      'losing a close friend.',
      'traveling alone.',
      'standing up for someone.',
      'surprising myself.',
    ],
  },
  {
    id: 'q4_2',
    section: 'Pivotal Experiences In My Life',
    sectionIndex: 6,
    text: 'I am most proud of...',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'the family I raised.',
      'my professional achievements.',
      'the person I\'ve become.',
      'the ways I\'ve helped others.',
      'my resilience in tough times.',
      'how I\'ve learned from my mistakes.',
      'my marriage and partnership.',
      'my children\'s accomplishments.',
      'serving my community.',
      'building lasting friendships.',
      'my faith and spiritual journey.',
      'my commitment to my values.',
      'how I\'ve grown wiser with age.',
      'mentoring younger people.',
      'creating financial security.',
      'caring for my parents as they aged.',
      'making time for joy and laughter.',
      'traveling and exploring the world.',
      'learning new skills throughout life.',
      'maintaining my health.',
      'staying true to who I am.',
      'writing or creating art.',
      'building a successful business.',
      'overcoming personal challenges.',
      'preserving family traditions.',
      'speaking up for what\'s right.',
      'being financially responsible.',
      'supporting friends in need.',
      'learning to forgive.',
      'maintaining optimism.',
      'being a good listener.',
      'teaching others valuable lessons.',
    ],
  },
  {
    id: 'q4_3',
    section: 'Pivotal Experiences In My Life',
    sectionIndex: 6,
    text: 'Give a short example or story about a pivotal moment in your life. This is probably a story that you find yourself repeating.',
    type: 'story',
    voiceEnabled: true,
    required: false,
    placeholder: 'Say it in your own words. Voice-to-Text highly recommended.',
    subtitle: 'Choose the first one that you connect to, and start talking.',
    storyTitle: 'Story 1',
    storyPrompts: [
      'What\'s a story you\'ve noticed you repeat a lot?',
      'What\'s the best financial decision you ever made?',
      'One thing I\'ve always wanted you to know about me is...',
      'What advice would you give someone starting their first job?',
      'People always ask me how I got rich and here\'s the real answer...',
      'What do you remember about your first paycheck?',
      'Tell me about your first big win — in life, business, or love.',
      'How did becoming a parent change you?',
      'What is a story from your military service that you\'ll carry with you always?',
      'What lessons did you learn when you went away to college?',
    ],
    allowAddMore: true,
  },

  // ============================================
  // Section 5: Guidance for Stewardship
  // ============================================
  {
    id: 'q5_2',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'It\'s important to me that my family understands the following about my financial intentions and values...',
    type: 'dropdown',
    required: false,
    placeholder: 'Say it in your own words.',
    options: [
      'I value education over material wealth.',
      'Wealth is a tool, not an identity.',
      'Family unity matters more than money.',
      'I want them to avoid unnecessary conflicts over money.',
      'I believe in generosity balanced with wisdom.',
      'Financial independence is important.',
      'Our family name carries responsibility.',
      'I want them to stay humble.',
      'I hope they help those less fortunate.',
      'I want them to invest in experiences, not just possessions.',
      'honesty and integrity matter in financial dealings.',
      'wealth should be used to create opportunities.',
      'stewardship means protecting what\'s been built.',
      'secrecy causes harm; open communication is better.',
      'I trust them to make good choices.',
      'Preserving wealth for future generations is important.',
      'Our traditions and stories are part of our wealth.',
      'mistakes with money are part of learning.',
      'It\'s okay to seek professional help.',
      'Wealth comes with responsibility.',
      'generosity should be given freely, not for recognition.',
      'it\'s important to leave something meaningful behind.',
      'preserving properties and heirlooms honors our past.',
      'simplicity and moderation are virtues.',
      'thoughtful giving is more powerful than reckless spending.',
      'planning for taxes is wise stewardship.',
      'Family relationships matter more than financial disputes.',
      'Legal planning is crucial to protect wealth.',
      'Knowledge is the best inheritance.',
      'every dollar should align with our values.',
      'Protecting privacy around wealth is critical.',
    ],
  },
  {
    id: 'q5_3',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'Regarding financial literacy, I hope my heirs will:',
    type: 'multiselect',
    required: false,
    placeholder: 'Select up to 5',
    options: [
      'spend the time to learn how to invest wisely.',
      'understand budgeting and saving.',
      'seek out financial education.',
      'teach their own children about money.',
      'ask questions and keep learning.',
      'know how taxes affect wealth.',
      'avoid high-interest debt.',
      'read books about personal finance.',
      'talk openly about money with family.',
      'stay cautious of financial scams.',
      'consult financial advisors.',
      'keep good financial records.',
      'understand how credit works.',
      'learn about different types of investments.',
      'manage property wisely.',
      'protect their credit scores.',
      'research big purchases carefully.',
      'plan for retirement early.',
      'save consistently over time.',
      'live within their means.',
      'build an emergency fund.',
      'understand how insurance protects wealth.',
      'think long-term about financial decisions.',
      'prioritize financial independence.',
      'avoid emotional spending.',
      'protect assets with legal planning.',
      'stay informed about financial laws.',
      'teach their partners financial skills.',
      'value experiences over things.',
      'protect the family legacy through learning.',
      'use technology to track their finances.',
    ],
  },
  {
    id: 'q5_5',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'When it comes to personal finance, here is the advice I want to pass on based on what I\'ve learned over the years:',
    type: 'dropdown',
    required: false,
    placeholder: 'Say it in your own words.',
    options: [
      'Spend less than you earn and save the difference consistently.',
      'Live on a written budget and give every dollar a job.',
      'Avoid debt whenever possible, especially high-interest debt.',
      'Start investing early and let compound interest do the heavy lifting.',
      'Own a piece of the market through low-cost index funds.',
      'Keep investing simple and don\'t chase trends.',
      'The market will go up and down — stay calm and stay the course.',
      'Focus on long-term goals, not short-term noise.',
      'Build an emergency fund before you invest aggressively.',
      'Make decisions when you\'re calm, not when you\'re emotional.',
      'Don\'t try to time the market — time in the market matters more.',
      'Diversify to reduce risk and protect your future.',
      'If you don\'t understand an investment, don\'t put your money into it.',
      'Know that wealth is built slowly and steadily, not overnight.',
      'Avoid financial fads and stick to proven strategies.',
      'Build assets, not liabilities.',
      'Don\'t confuse busyness with productivity — invest your energy wisely.',
      'Your career is your most important early investment.',
      'Protect your assets through estate planning and insurance.',
      'Give generously — money is most powerful when it has purpose.',
      'Keep learning about money your whole life.',
      'Stick to your plan even when others are panicking.',
      'Be patient. Wealth grows over decades, not days.',
      'Know the difference between speculation and investing.',
      'Protect your future self by making disciplined choices today.',
      'Know your "enough" — wealth is not the same as happiness.',
      'Hire help when needed, but stay informed and in control.',
      'Pigs get fed, hogs get slaughtered. Don\'t be greedy — remember that risk and reward go hand in hand.',
      'Invest in your health first, also your education and your relationships.',
      'Money can open doors, but character is what keeps them open.',
    ],
  },
  {
    id: 'q5_6',
    section: 'Guidance For Stewardship',
    sectionIndex: 2,
    text: 'I wish to provide the following general guidance for my heirs to make the most of their inheritance:',
    type: 'dropdown',
    required: false,
    placeholder: 'Say it in your own words.',
    options: [
      'Use this inheritance to build a strong foundation for your future.',
      'Invest thoughtfully and with a long-term perspective.',
      'Seek professional financial advice before making big decisions.',
      'Pay off debt and avoid unnecessary new obligations.',
      'Spend on experiences that create lasting memories.',
      'Use these resources to pursue your education or career goals.',
      'Remember that wealth is a tool, not a destination.',
      'Make choices that align with your values, not social expectations.',
      'Set aside funds for emergencies and future security.',
      'Share your good fortune with others through generosity.',
      'Use what you\'ve received to create opportunities for others.',
      'Be mindful not to let money change who you are.',
      'Work to preserve and grow this inheritance for the next generation.',
      'Use part of your inheritance to give back to your community.',
      'Consider using trusts or legal tools to manage your own estate.',
      'Talk openly with your family about financial goals and plans.',
      'Keep your lifestyle grounded and sustainable.',
      'Avoid making rushed or emotional financial decisions.',
      'Protect your privacy and your assets wisely.',
      'Stay humble, no matter your wealth.',
      'Continue learning about personal finance and wealth management.',
      'Teach your children what responsible stewardship looks like.',
      'Support causes that matter to you.',
      'Don\'t be afraid to say "no" when needed—even to family or friends.',
      'Balance enjoying today with preparing for tomorrow.',
      'Value people over possessions.',
      'Remember that what you do with this gift reflects who you are.',
      'Maintain the integrity of family heirlooms and property.',
      'Be generous, but also discerning.',
      'Live simply, give freely, and plan carefully.',
      'Treat this inheritance as both a gift and a responsibility.',
      'Honor my efforts by living a life of meaning and purpose.',
      'Do your best to avoid paying excess taxes on any of this. Get help when you need it.',
    ],
  },
  {
    id: 'q5_asset_section',
    section: 'The Story Behind My Gifts',
    sectionIndex: 3,
    text: 'Your Assets & Gifts',
    label: 'What becomes yours after I\'m gone',
    type: 'asset-section',
    required: false,
  },

  // ============================================
  // Section 6: My Legacy
  // ============================================
  {
    id: 'q6_1',
    section: 'My Legacy',
    sectionIndex: 7,
    text: 'I hope to be remembered for...',
    label: 'Select up to 3',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    maxSelections: 3,
    options: [
      'how deeply I loved.',
      'the way I showed up for others.',
      'the values I lived by.',
      'how I made people feel seen and heard.',
      'my honesty and integrity.',
      'my generosity with time and resources.',
      'my sense of humor.',
      'the way I brought people together.',
      'my faith and spiritual convictions.',
      'the traditions I passed down.',
      'how I stayed true to myself.',
      'the lessons I taught my family.',
      'the way I listened.',
      'my strength during hard times.',
      'my commitment to justice and fairness.',
      'my creativity and unique perspective.',
      'the warmth I brought into every space.',
      'my ability to forgive and ask for forgiveness.',
      'the joy I found in simple things.',
      'how I served my community.',
      'how I lifted others up.',
      'my love for learning.',
      'the memories I created with loved ones.',
      'how I prioritized relationships over things.',
      'the quiet strength I offered.',
      'my cooking, and my comfort level in the kitchen.',
      'the wisdom I tried to share.',
      'my deep love for family.',
      'my steady presence through life\'s ups and downs.',
      'my laughter.',
      'the faith I kept.',
      'the hope I passed on.',
    ],
  },
  {
    id: 'q6_2',
    section: 'My Legacy',
    sectionIndex: 7,
    text: 'The causes that have always been important to me are...',
    type: 'multi-dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'advancing social justice.',
      'protecting the environment.',
      'promoting education and mentorship.',
      'supporting healthcare and well-being.',
      'helping the homeless.',
      'animal welfare.',
      'mental health awareness.',
      'ending hunger and poverty.',
      'supporting veterans.',
      'fostering community arts.',
      'children\'s welfare.',
      'disaster relief efforts.',
      'clean water initiatives.',
      'preserving historic places.',
      'fighting human trafficking.',
      'global health issues.',
      'supporting immigrants and refugees.',
      'women\'s rights.',
      'LGBTQ+ rights.',
      'prison reform.',
      'literacy programs.',
      'sustainable farming.',
      'elder care and advocacy.',
      'affordable housing.',
      'voting rights and democracy.',
      'religious freedom.',
      'civil liberties.',
      'cultural preservation.',
      'youth sports and development.',
      'hospice care.',
      'supporting foster youth.',
      'financial literacy education.',
    ],
  },
  {
    id: 'q6_3',
    section: 'My Legacy',
    sectionIndex: 7,
    text: 'I hope that my family will carry forward this guiding purpose or legacy',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Build generational wealth',
      'Be wealthier as a family than we are today, 100 years from now',
      'Honor our roots and build our future',
      'Live with integrity and intention',
      'Grow love, legacy, and leadership',
      'Protect and pass down wisdom',
      'Preserve assets for historical value',
      'Spread the word of God',
      'Put education first',
      'Uplift every generation',
      'Be stewards of faith and fortune',
      'Nurture character over comfort',
      'Leave every place better than we found it',
      'Give generously, live humbly',
      'Invest in people and purpose',
      'Build a family of builders',
      'Lead with love and loyalty',
      'Preserve our story, protect our values',
      'Multiply what matters',
      'Pass on more than possessions',
      'Strengthen our name for generations to come',
    ],
  },
  {
    id: 'q6_4',
    section: 'My Legacy',
    sectionIndex: 7,
    text: 'What does it mean to be part of this family? If you had a vote to choose your Family Core Values after you are gone, which would you choose?',
    label: 'Select up to 3',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    maxSelections: 3,
    options: [
      'Faith', 'Family', 'Integrity', 'Hard Work', 'Love',
      'Loyalty', 'Service', 'Education', 'Generosity', 'Humility',
      'Perseverance', 'Respect', 'Gratitude', 'Courage', 'Kindness',
      'Honesty', 'Wisdom', 'Unity', 'Hope', 'Compassion',
    ],
  },
  {
    id: 'q6_5',
    section: 'My Legacy',
    sectionIndex: 7,
    text: 'If my family created a physical memorial in my honor, what appeals to me most is',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'my ashes scattered in a beautiful location that you enjoy visiting with family',
      'a park bench beneath the trees',
      'a constellation named after me',
      'a grave stone is enough',
      'my ashes mounted into quality jewelry and distributed to my immediate family',
      'my ashes stored in a tiny hourglass and used as a timer during family game night',
      'a child who carries my name',
      'a quiet visit to where I rest',
      'a tree planted in my honor',
      'a plaque at our local library',
      'a scholarship fund in my name at my alma mater',
      'a memorial garden in a favorite place',
      'my name on a community center wall',
      'a donation to a museum or cultural site',
      'a commemorative brick at the botanical gardens',
      'a walking trail or path dedicated in my memory',
      'a street or alley named after me',
      'a memorial tile at a favorite sports stadium',
      'a family recipe engraved in stone',
      'my name included in a time capsule',
      'a personalized bench at my alma mater',
      'a swing in a neighborhood park',
      'a collection of my letters or journals archived',
      'an annual gathering or family picnic in my name',
      'a memorial tree grove for future generations',
      'a sculpture or public art piece',
      'a painted mural that tells part of my story',
      'my name on a donor wall at a hospital',
      'a community fridge or pantry donated in my honor',
      'a bench at the beach I loved',
      'a memorial stone placed on family land',
      'a piece of jewelry passed down through generations',
      'a cabin, house, or property preserved in the family name',
      'a song, poem, or story written in my memory',
    ],
  },

  // ============================================
  // Section 7: Final Thoughts
  // ============================================
  {
    id: 'q7_1',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'Above all, I want you to know...',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'how much I love you.',
      'that I\'ve always been proud of you.',
      'that my love doesn\'t end with this letter.',
      'how grateful I am to have had you in my life.',
      'that I see the best parts of me in you.',
      'that you made my life better by being in it.',
      'how much joy you brought me.',
      'that I\'ve carried you in my heart every day.',
      'that you were one of my greatest gifts.',
      'how often I thought of you even when I didn\'t say it.',
      'that our memories are my treasures.',
      'that I trust you to carry my values forward.',
      'how proud I am of the person you\'ve become.',
      'that I wish you peace, always.',
      'that my hope for you is lifelong happiness.',
      'that love is what matters most.',
      'that I never stopped rooting for you.',
      'how lucky I felt to be your parent.',
      'that you are enough, exactly as you are.',
      'that your presence in my life was a blessing.',
      'that I want you to live a full, beautiful life.',
      'that I\'ve made peace with my journey.',
      'that I tried to live by example.',
      'that you can always return to my words for comfort.',
      'that the bond we share is forever.',
      'that I hope you\'ll tell your children about me.',
      'that everything I did, I did out of love.',
      'that you can find strength in your own story.',
      'that I believe in you.',
      'that this letter is my way of holding your hand once more.',
    ],
  },
  {
    id: 'q7_2',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'If you ever find yourself in a hard season, I hope you will remember',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'you\'ve made it through hard times before.',
      'you are stronger than you think.',
      'you are never alone.',
      'I\'ve been through darkness too, and I found my way.',
      'that love surrounds you, even in silence.',
      'you can begin again.',
      'that hope always returns.',
      'you don\'t have to carry everything by yourself.',
      'there\'s no shame in asking for help.',
      'this moment will pass.',
      'your story isn\'t over yet.',
      'healing is never linear.',
      'light still exists, even if you can\'t see it now.',
      'peace often follows persistence.',
      'you can break down and still rebuild.',
      'your feelings are valid.',
      'just one breath at a time is enough.',
      'you don\'t have to be perfect — just present.',
      'my love is still with you.',
      'that grief is love looking for somewhere to go.',
      'you were never meant to carry this alone.',
      'strength is quiet sometimes.',
      'there is always tequila. Cheers.',
      'that I would sit beside you, if I could.',
      'that you have what you need to get through.',
      'even the worst days won\'t last forever.',
      'that being gentle with yourself is powerful.',
      'storms pass — always.',
      'you are allowed to rest.',
      'the sun still rises.',
      'you matter.',
    ],
  },
  {
    id: 'q7_3',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'My advice for how to handle challenges in life is...',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'to stay calm and take things one step at a time.',
      'to lean on family and friends when you need help.',
      'to remember that hard times don\'t last forever.',
      'to keep faith in yourself and in something greater.',
      'to look for the lesson in every hardship.',
      'to take care of your mental health.',
      'to never be afraid to ask for help.',
      'to focus on what you can control.',
      'to believe that better days will come.',
      'to keep a sense of humor, even in tough times.',
      'to be gentle with yourself during struggles.',
      'to pray or meditate for guidance.',
      'to forgive yourself for mistakes.',
      'to write things down when you\'re overwhelmed.',
      'to exercise and stay physically healthy.',
      'to stay connected with people who care.',
      'to keep your perspective and not lose hope.',
      'to avoid making big decisions in emotional moments.',
      'to trust that time can heal wounds.',
      'to let go of what you can\'t change.',
      'to find comfort in small daily routines.',
      'to learn from past experiences.',
      'to count your blessings, even during trials.',
      'to seek professional help when needed.',
      'to maintain your integrity, no matter the challenge.',
      'to face problems with courage and honesty.',
      'to remind yourself that you\'ve overcome things before.',
      'to stay patient and persistent.',
      'to believe in your own resilience.',
      'to find solace in helping others.',
      'to know that feelings are temporary.',
      'to accept that life has seasons of both joy and sorrow.',
    ],
  },
  {
    id: 'q7_4',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'One message I want to pass on to the next generation is...',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'You are loved — always, and without condition.',
      'Keep going — your life has purpose.',
      'Stay true to your values no matter the pressure.',
      'Build a life that feels right to you.',
      'Never stop learning, growing, and becoming.',
      'Listen to your inner voice — it\'s wiser than you think.',
      'Be kind — even when it\'s hard.',
      'Choose love over fear.',
      'Stay curious.',
      'Stand up for what\'s right.',
      'Keep your word.',
      'Take care of your soul.',
      'Stay close to the people who know your heart.',
      'Let faith guide you, even in uncertainty.',
      'Don\'t rush — good things take time.',
      'Laugh often and out loud.',
      'Invest in your people — they\'re your true wealth.',
      'Apologize quickly and forgive freely.',
      'Make room for joy.',
      'Chase your dreams with courage.',
      'Protect your peace.',
      'Make decisions you\'ll be proud of years from now.',
      'Trust that you are enough.',
      'Take responsibility for your actions.',
      'Take care of your mind, body, and spirit.',
      'Remember where you came from.',
      'Be a good steward of your blessings.',
      'Choose meaning over convenience.',
      'Give more than you take.',
      'Leave the world better than you found it.',
    ],
  },
  {
    id: 'q7_6',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'One last thing I\'d like to say is...',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'thank you for loving me.',
      'thank you for letting me love you.',
      'I carry no regrets about loving you.',
      'I leave you with my full heart.',
      'I\'m proud of our time together.',
      'I\'ll always be with you in spirit.',
      'this letter is a part of me I\'m leaving behind.',
      'I hope you\'ll find comfort in these words.',
      'I\'ll be cheering you on from wherever I am.',
      'please continue building a life you love.',
      'keep telling your story.',
      'live bravely and with purpose.',
      'forgive me for any times I fell short.',
      'remember me with laughter, not only tears.',
      'keep our traditions alive.',
      'love each other fiercely.',
      'create your own legacy.',
      'find peace in your own way.',
      'visit the places that brought me joy.',
      'keep looking for beauty in the world.',
      'trust your heart.',
      'be good to each other.',
      'stay close to the people who matter.',
      'love will always guide you.',
      'remember that I believed in you.',
      'I\'m proud of all that you\'ve done.',
      'continue to grow.',
      'know that I left nothing unsaid.',
      'carry this letter forward.',
      'I love you — always.',
    ],
  },
  {
    id: 'q7_7',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'Closing for your letter',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'With all my love',
      'Love always',
      'Forever yours',
      'Holding you in my heart',
      'Peace and love',
      'With a full heart',
      'Your [mother/father/grandparent/etc.], always',
      'All my love, now and always',
      'Until the sun comes down on me',
      'Until we meet again',
      'In the quiet moments, I\'ll be there',
      'Still with you, just beyond the veil',
      'Beneath the same sky',
      'May love be your guide',
      'In every heartbeat, I\'m near',
      'Sincerely',
      'Yours truly',
      'Faithfully',
      'With gratitude',
      'Ever yours',
      'Respectfully',
      'Affectionately',
      'In the spirit of our family',
      'Passing the torch',
      'As your guide from afar',
      'From my life to yours',
      'Signing off, but never gone',
      'Rooted in legacy',
      'May this be my final gift',
    ],
    allowCustom: true,
  },
  {
    id: 'q7_5',
    section: 'Final Thoughts',
    sectionIndex: 8,
    text: 'What name do you want to use to sign your letter?',
    type: 'text',
    required: false,
    placeholder: 'Type Here',
  },

  // ============================================
  // Section 8: Tone & Voice of Questionnaire
  // ============================================
  {
    id: 'q8_1',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Overall Feel',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Calm and reflective',
      'Warm and affectionate',
      'Direct and to the point',
      'Formal and traditional',
      'Gentle and balanced — not too emotional, not too stiff',
    ],
  },
  {
    id: 'q8_2',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Emotional Expression',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Strong emotional warmth',
      'Moderate emotion, controlled',
      'Soft, subtle emotion only',
      'Minimal — keep emotion restrained',
    ],
  },
  {
    id: 'q8_3',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Sentence Style',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Short, clean sentences — "say it simply"',
      'Medium-length, natural paragraphs',
      'Full expressive paragraphs with more detail',
    ],
  },
  {
    id: 'q8_4',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Warmth Level',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Very warm and personal',
      'Warm but measured',
      'Neutral and balanced',
      'Cool / reserved / not sentimental',
    ],
  },
  {
    id: 'q8_5',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Formality Level',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Casual, everyday language',
      'Professional but friendly',
      'Traditional and formal wording',
      'Very polished / ceremonial tone',
    ],
  },
  {
    id: 'q8_6',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Directness',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Blunt and direct — no extra words',
      'Clear and matter-of-fact',
      'Thoughtful and gentle in how you say things',
      'Very cautious and diplomatic with wording',
    ],
  },
  {
    id: 'q8_7',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Do you want faith-based or spiritual language included in the letter?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Yes, prominently',
      'Yes, but subtle references only',
      'Only if it arises naturally from my story',
      'No, exclude all faith/spiritual language',
    ],
  },
  {
    id: 'q8_9',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Optional: If you want references from a specific faith tradition (Christian, Jewish, Buddhist, etc.),',
    type: 'text',
    required: false,
    placeholder: 'Type Here',
  },
  {
    id: 'q8_10',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Optional: How explicitly should that tradition be referenced?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Light references only (values, worldview, not scripture)',
      'Moderate (beliefs and God-language acceptable)',
      'Strong / Faith-centered tone',
    ],
  },
  {
    id: 'q8_11',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'How personally revealing should the letter be?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'High — share candid feelings and vulnerabilities',
      'Medium — some openness but not deep',
      'Low — keep it polite and surface-level',
    ],
  },
  {
    id: 'q8_12',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Use of Figurative / Poetic Language',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'I like expressive wording and gentle imagery',
      'I like language with warmth but not poetic',
      'Avoid metaphors — be literal and plain',
    ],
  },
  {
    id: 'q8_13',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'How do you want to sound in relation to the recipients?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Loving parent or grandparent — "I am so proud of you."',
      'Wise mentor or advisor — "Here is what experience taught me."',
      'Equal adult peer — "From one adult to another…"',
      'Formal benefactor / steward — "I entrust this with intention."',
      'Protective or cautioning voice — "Please don\'t repeat my mistakes."',
      'Humble, grateful elder — "I have received more than I gave."',
      'Reconciliatory bridge-builder — "I want peace between us."',
    ],
  },
  {
    id: 'q8_14',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'How "dense" should the writing feel?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Light and spacious — more white space, fewer words',
      'Moderate — balanced length',
      'Dense — detailed and fully explained, get in as much as you can',
    ],
  },
  {
    id: 'q8_15',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Should we use contractions?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Yes — natural and conversational',
      'No — write out full words (I am, I will)',
    ],
  },
  {
    id: 'q8_16',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Which tones should we absolutely avoid?',
    type: 'multiselect',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Flowery or poetic',
      'Cold or mechanical',
      'Overly emotional',
      'Legalistic or stiff',
      'Preachy or moralizing',
      'Nostalgic or sentimental',
      'None — I\'m open to any as long as it feels natural',
    ],
    allowCustom: true,
  },
  {
    id: 'q8_17',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'Which font would you like to use?',
    type: 'dropdown',
    required: false,
    placeholder: 'Select the best answer',
    options: [
      'Classic Serif (Times New Roman)',
      'Modern Sans-Serif (Arial)',
      'Elegant Script',
      'Traditional Typewriter',
      'Handwritten Style',
    ],
  },
  {
    id: 'q8_18',
    section: 'Tone & Voice of Questionnaire',
    sectionIndex: 9,
    text: 'If you selected Handwritten Style, which handwriting do you prefer?',
    type: 'handwriting-style',
    required: false,
    placeholder: 'Select a handwriting style',
    options: [
      'Style 1 - Casual Script',
      'Style 2 - Elegant Cursive',
      'Style 3 - Modern Handwriting',
      'Style 4 - Classic Penmanship',
    ],
  },
];

// Helper function to get questions by section
export const getQuestionsBySection = (sectionIndex: number): Question[] => {
  return questions.filter(q => q.sectionIndex === sectionIndex);
};

// Helper function to get section info
export const getSectionByIndex = (index: number): Section | undefined => {
  return sections.find(s => s.id === index);
};

// IDs of questions that are explicitly optional (user doesn't need to answer to proceed)
// These include: secondary stories, child/spouse sections, optional fields marked in text
const OPTIONAL_QUESTION_IDS = [
  'q2_4b',              // Story 2 (secondary story)
  'q3_children_section', // Children section (not everyone has children)
  'q3_spouse_section',   // Spouse section (not everyone has a spouse)
  'q5_8',               // Gift Story (voice/optional story)
  'q8_9',               // Optional faith tradition text
  'q8_10',              // Optional faith reference level
];

// Check if a question is optional
export const isQuestionOptional = (question: Question): boolean => {
  // Explicitly optional questions
  if (OPTIONAL_QUESTION_IDS.includes(question.id)) {
    return true;
  }

  // Story type questions with storyTitle containing "Story 2", "Story 3", etc. are optional
  if (question.type === 'story' && question.storyTitle) {
    const storyNum = question.storyTitle.match(/Story (\d+)/);
    if (storyNum && parseInt(storyNum[1]) > 1) {
      return true;
    }
  }

  // Additional stories (dynamically added) are optional
  if (question.id.includes('_additional_')) {
    return true;
  }

  return false;
};

// Get required questions for a section (questions that must be answered to proceed)
export const getRequiredQuestionsForSection = (sectionIndex: number): Question[] => {
  return getQuestionsBySection(sectionIndex).filter(q => !isQuestionOptional(q));
};

// Check if all required questions in a section are answered
export const isSectionComplete = (
  sectionIndex: number,
  answers: Record<string, string | string[]>
): boolean => {
  const requiredQuestions = getRequiredQuestionsForSection(sectionIndex);

  return requiredQuestions.every(question => {
    const answer = answers[question.id];

    // Check if answer exists and is not empty
    if (answer === undefined || answer === null) {
      return false;
    }

    // Handle array answers (multiselect)
    if (Array.isArray(answer)) {
      return answer.length > 0;
    }

    // Handle string answers
    if (typeof answer === 'string') {
      return answer.trim() !== '';
    }

    return false;
  });
};